name: quote_repository
publish_to: none
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  fav_qs_api:
    path: ../fav_qs_api
  key_value_storage:
    path: ../key_value_storage
  domain_models:
    path: ../domain_models

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.24.3
  lints: ^4.0.0
