name: user_repository
publish_to: none
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  fav_qs_api:
    path: ../fav_qs_api
  key_value_storage:
    path: ../key_value_storage
  domain_models:
    path: ../domain_models
  rxdart: ^0.28.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  mockito: ^5.2.0
  test: ^1.24.3
  lints: ^4.0.0
  build_runner: ^2.0.5