name: key_value_storage
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  hive: 2.2.3
  path_provider: ^2.0.2

dev_dependencies:
  build_runner: ^2.0.5
  hive_generator: ^2.0.1
  lints: 4.0.0
  test: ^1.24.3