name: quote_list
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  component_library:
    path: ../../component_library
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  flutter:
    sdk: flutter
  domain_models:
    path: ../../domain_models
  quote_repository:
    path: ../../quote_repository
  user_repository:
    path: ../../user_repository
  monitoring:
    path: ../../monitoring
  infinite_scroll_pagination: ^4.0.0-dev.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.1.4
  test: ^1.16.8
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true