name: forgot_my_password
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  component_library:
    path: ../../component_library
  flutter_bloc: ^8.1.6
  flutter:
    sdk: flutter
  user_repository:
    path: ../../user_repository
  form_fields:
    path: ../../form_fields

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  test: ^1.25.2
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true