name: form_fields
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  formz: ^0.4.1
  equatable: ^2.0.3

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8